# Generated by Django 5.1.1 on 2024-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessons_options_lessons_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['custom_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='lessons',
            name='custom_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
